# Read SQL databases using JDBC

- Databricks Runtime contains JDBC drivers for Microsoft SQL Server and Azure SQL Database

## Establish connectivity to SQL Server

### Create the JDBC URL

In [0]:
jdbcHostname = "dbsqlsvrmay22.database.windows.net"
jdbcDatabase = "dbsql"
jdbcPort = 1433
jdbcUsername = "atingupta2005"
jdbcPassword = "Azure@123456"

In [0]:
jdbcUrl = "jdbc:sqlserver://{0}:{1};database={2}".format(jdbcHostname, jdbcPort, jdbcDatabase)
connectionProperties = {
  "user" : jdbcUsername,
  "password" : jdbcPassword,
  "driver" : "com.microsoft.sqlserver.jdbc.SQLServerDriver"
}
print(jdbcUrl)
print(connectionProperties)

## Read data from JDBC

In [0]:
pushdown_query = "(select * from employees where employee_id < 105) emp_alias"
employees_table = spark.read.jdbc(url=jdbcUrl, table=pushdown_query, properties=connectionProperties)
display(employees_table)

employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,manager_id,department_id
100,Steven,King,steven.king@sqltutorial.org,515.123.4567,1987-06-17,4,24000.00,null,9
101,Neena,Kochhar,neena.kochhar@sqltutorial.org,515.123.4568,1989-09-21,5,17000.00,100,9
102,Lex,De Haan,lex.de haan@sqltutorial.org,515.123.4569,1993-01-13,5,17000.00,100,9
103,Alexander,Hunold,alexander.hunold@sqltutorial.org,590.423.4567,1990-01-03,9,9000.00,102,6
104,Bruce,Ernst,bruce.ernst@sqltutorial.org,590.423.4568,1991-05-21,9,6000.00,103,6

In [0]:
df.printSchema

In [0]:
display(employees_table.select("manager_id", "salary").groupBy("manager_id").avg("salary"))

manager_id,avg(salary)
103,6000.000000
null,24000.000000
100,17000.000000
102,9000.000000

## Write data to JDBC

In [0]:
employees_table.write.jdbc(url=jdbcUrl, table="employee2", properties=connectionProperties, mode="overwrite")